# <span style="color:cyan"> **Análise Exploratória**</span>

## **Disciplina:** Ciência de Dados II

### **Aluno:** Mykael Querido Marinho da Silva

A ideia dessa introdução ao projeto é fazer uma análise exploratório da base de dados, por meio de estatística descritiva.

A base de dados utilizada para o projeto é a de Microdados do Enem 2024, publicados pelo Instituto Nacional de Estudos e Pesquisas Anísio Teixeira (INEP). Disponível em: https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/microdados

In [9]:
# Importando bibliotecas necessárias
import os
import sys
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

### Conhecendo os dados

Os dados do Enem são disponibilizados com granularidade por estudante, sendo cada linha da base referente às notas de um estudante.

In [32]:
# caminho relativo ao notebook
path = "C:\\Users\\mykaq\\Desktop\\Estudos\\Unifesp\\Ciência de Dados II\\Projeto\\cd2_analise_enem\\data\\raw\\RESULTADOS_2024.csv"

df_enem = pd.read_csv(
    path,
    sep=";",
    encoding="latin1"
)

df_enem.head()

,NU_SEQUENCIAL,NU_ANO,CO_ESCOLA,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,...,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO
0,206403,2024,23052929.0,2301406.0,Aratuba,23.0,CE,2.0,1.0,1.0,...,CECEBEBCDBADDEBBABCDCAECEDADBAEABEADCEDADACBC,CAAAECDDDAECBECEDDCBDEDDCECBDCBCEADBBDBDDCBEDA...,CECEBEDADCAADECDBBCEBDCCCACABBABBADDDCEADBBCE,1.0,80.0,60.0,60.0,80.0,20.0,300.0
1,3604651,2024,42103770.0,4218004.0,Tijucas,42.0,SC,4.0,1.0,1.0,...,DADABCDCECEDEBBBEBCDBADACBCADCEBEADBAECAECEDA,AACEADDDACDADECBBDBEEBDDECCBEDDCADBBDEBCEBDCEC...,DBCECEACADABBECBEDADCCDCCABBBCECEBCEADABBADDD,1.0,160.0,200.0,200.0,180.0,180.0,920.0
2,1461268,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CAEDBADBEBCCEDADBAEACBCADCEDEBBEBACECEABCDDAD,EAAACDDCDADDCBDEECEECBDCDADEEBCBEBADBCEBDBDDDD...,ABBABBADDDBBCECEADCEBCCCDBADCBEDAECADACDBCECE,1.0,120.0,120.0,40.0,120.0,80.0,480.0
3,4301058,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ACBCADCEDBAECEDADBADBEBCDADABCDEABCAEDEBBCECE,AACEADACDDCBEDADEEBDDBDBBCEECBDCBADDDCBDEDDCEC...,CEBCEADBBCEADDDABBABBCCDCCECEDBACADECABEDADCB,1.0,140.0,200.0,160.0,160.0,80.0,740.0
4,3148322,2024,21150354.0,2100436.0,Alto Alegre do Maranhão,21.0,MA,2.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
df_enem.shape
df_enem.columns.tolist()
df_enem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4332944 entries, 0 to 4332943
Data columns (total 42 columns):
 #   Column                  Dtype
---  ------                  -----
 0   NU_SEQUENCIAL           int64
 1   NU_ANO                  int64
 2   CO_ESCOLA               float64
 3   CO_MUNICIPIO_ESC        float64
 4   NO_MUNICIPIO_ESC        object
 5   CO_UF_ESC               float64
 6   SG_UF_ESC               object
 7   TP_DEPENDENCIA_ADM_ESC  float64
 8   TP_LOCALIZACAO_ESC      float64
 9   TP_SIT_FUNC_ESC         float64
 10  CO_MUNICIPIO_PROVA      int64
 11  NO_MUNICIPIO_PROVA      object
 12  CO_UF_PROVA             int64
 13  SG_UF_PROVA             object
 14  TP_PRESENCA_CN          int64
 15  TP_PRESENCA_CH          int64
 16  TP_PRESENCA_LC          int64
 17  TP_PRESENCA_MT          int64
 18  CO_PROVA_CN             float64
 19  CO_PROVA_CH             float64
 20  CO_PROVA_LC             float64
 21  CO_PROVA_MT             float64
 22  NU_NOTA_CN              float64
 23  NU_NOTA_CH              float64
 24  NU_NOTA_LC              float64
 25  NU_NOTA_MT              float64
 26  TX_RESPOSTAS_CN         object
 27  TX_RESPOSTAS_CH         object
 28  TX_RESPOSTAS_LC         object
 29  TX_RESPOSTAS_MT         object
 30  TP_LINGUA               int64
 31  TX_GABARITO_CN          object
 32  TX_GABARITO_CH          object
 33  TX_GABARITO_LC          object
 34  TX_GABARITO_MT          object
 35  TP_STATUS_REDACAO       float64
 36  NU_NOTA_COMP1           float64
 37  NU_NOTA_COMP2           float64
 38  NU_NOTA_COMP3           float64
 39  NU_NOTA_COMP4           float64
 40  NU_NOTA_COMP5           float64
 41  NU_NOTA_REDACAO         float64
dtypes: float64(21), int64(9), object(12)
memory usage: 1.4+ GB

In [34]:
# Filtrando apenas alunos com presença confirmada e notas válidas
df_enem = df_enem[df_enem['TP_PRESENCA_CN'] == 1]
df_enem = df_enem[df_enem['TP_PRESENCA_CH'] == 1]
df_enem = df_enem[df_enem['TP_PRESENCA_LC'] == 1]
df_enem = df_enem[df_enem['TP_PRESENCA_MT'] == 1]

In [35]:
cols = [
    "NU_SEQUENCIAL",
    "CO_ESCOLA",
    "CO_MUNICIPIO_ESC",
    "NO_MUNICIPIO_ESC",
    "CO_UF_ESC",
    "TP_DEPENDENCIA_ADM_ESC",
    "TP_LOCALIZACAO_ESC",
    "TP_SIT_FUNC_ESC",
    "NU_NOTA_MT",
    "NU_NOTA_CN",
    "NU_NOTA_CH",
    "NU_NOTA_LC",
    "NU_NOTA_REDACAO",
    "NU_NOTA_COMP1",
    "NU_NOTA_COMP2",
    "NU_NOTA_COMP3",
    "NU_NOTA_COMP4",
    "NU_NOTA_COMP5"
]

# Editando o DataFrame para manter apenas as colunas de interesse
df_enem_filtrado = df_enem[cols]

In [36]:
# Ajustando tipos de dados
df_enem_filtrado['NU_SEQUENCIAL'] = df_enem_filtrado['NU_SEQUENCIAL'].astype(str)
df_enem_filtrado['CO_ESCOLA'] = df_enem_filtrado['CO_ESCOLA'].astype(str)
df_enem_filtrado['CO_MUNICIPIO_ESC'] = df_enem_filtrado['CO_MUNICIPIO_ESC'].astype(str)
df_enem_filtrado['CO_UF_ESC'] = df_enem_filtrado['CO_UF_ESC'].astype(str)
df_enem_filtrado['TP_DEPENDENCIA_ADM_ESC'] = df_enem_filtrado['TP_DEPENDENCIA_ADM_ESC'].astype(str)
df_enem_filtrado['TP_LOCALIZACAO_ESC'] = df_enem_filtrado['TP_LOCALIZACAO_ESC'].astype(str)
df_enem_filtrado['TP_SIT_FUNC_ESC'] = df_enem_filtrado['TP_SIT_FUNC_ESC'].astype(str)

C:\Users\mykaq\AppData\Local\Temp\ipykernel_2928\4156567832.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_enem_filtrado['NU_SEQUENCIAL'] = df_enem_filtrado['NU_SEQUENCIAL'].astype(str)
C:\Users\mykaq\AppData\Local\Temp\ipykernel_2928\4156567832.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_enem_filtrado['CO_ESCOLA'] = df_enem_filtrado['CO_ESCOLA'].astype(str)
C:\Users\mykaq\AppData\Local\Temp\ipykernel_2928\4156567832.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_enem_filtrado['CO_MUNICIPIO_ESC'] = df_enem_filtrado['CO_MUNICIPIO_ESC'].astype(str)
C:\Users\mykaq\AppData\Local\Temp\ipykernel_2928\4156567832.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_enem_filtrado['CO_UF_ESC'] = df_enem_filtrado['CO_UF_ESC'].astype(str)
C:\Users\mykaq\AppData\Local\Temp\ipykernel_2928\4156567832.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_enem_filtrado['TP_DEPENDENCIA_ADM_ESC'] = df_enem_filtrado['TP_DEPENDENCIA_ADM_ESC'].astype(str)
C:\Users\mykaq\AppData\Local\Temp\ipykernel_2928\4156567832.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_enem_filtrado['TP_LOCALIZACAO_ESC'] = df_enem_filtrado['TP_LOCALIZACAO_ESC'].astype(str)
C:\Users\mykaq\AppData\Local\Temp\ipykernel_2928\4156567832.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_enem_filtrado['TP_SIT_FUNC_ESC'] = df_enem_filtrado['TP_SIT_FUNC_ESC'].astype(str)

In [37]:
# Estatística descritiva para colunas numéricas
df_enem_filtrado.describe()

,NU_NOTA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5
count,2.990093e+06,2.990093e+06,2.990093e+06,2.990093e+06,2.990093e+06,2.990093e+06,2.990093e+06,2.990093e+06,2.990093e+06,2.990093e+06
mean,5.270813e+02,4.940260e+02,5.142128e+02,5.266217e+02,6.346660e+02,1.212311e+02,1.466827e+02,1.198078e+02,1.309298e+02,1.160145e+02
std,1.141715e+02,7.898947e+01,9.155594e+01,6.865750e+01,2.090954e+02,3.602026e+01,4.617845e+01,4.117161e+01,4.456412e+01,6.171381e+01
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,4.313000e+02,4.315000e+02,4.502000e+02,4.867000e+02,5.200000e+02,1.000000e+02,1.200000e+02,1.000000e+02,1.200000e+02,8.000000e+01
50%,4.992000e+02,4.885000e+02,5.194000e+02,5.334000e+02,6.400000e+02,1.200000e+02,1.600000e+02,1.200000e+02,1.200000e+02,1.200000e+02
75%,6.110000e+02,5.503000e+02,5.785000e+02,5.736000e+02,8.000000e+02,1.400000e+02,1.800000e+02,1.400000e+02,1.600000e+02,1.600000e+02
max,9.619000e+02,8.672000e+02,8.197000e+02,7.958000e+02,1.000000e+03,2.000000e+02,2.000000e+02,2.000000e+02,2.000000e+02,2.000000e+02

In [38]:
# Criando média geral das notas
df_enem_filtrado['NU_NOTA_MEDIA_GERAL'] = df_enem_filtrado[[
    "NU_NOTA_MT",
    "NU_NOTA_CN",
    "NU_NOTA_CH",
    "NU_NOTA_LC",
    "NU_NOTA_REDACAO"
]].mean(axis=1)

# Criando média das objetivas (sem redação)
df_enem_filtrado['NU_NOTA_MEDIA_OBJETIVAS'] = df_enem_filtrado[[
    "NU_NOTA_MT",
    "NU_NOTA_CN",
    "NU_NOTA_CH",
    "NU_NOTA_LC"
]].mean(axis=1)

df_enem_filtrado.head(5)

C:\Users\mykaq\AppData\Local\Temp\ipykernel_2928\2842149023.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_enem_filtrado['NU_NOTA_MEDIA_GERAL'] = df_enem_filtrado[[
C:\Users\mykaq\AppData\Local\Temp\ipykernel_2928\2842149023.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_enem_filtrado['NU_NOTA_MEDIA_OBJETIVAS'] = df_enem_filtrado[[

,NU_SEQUENCIAL,CO_ESCOLA,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,NU_NOTA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_MEDIA_GERAL,NU_NOTA_MEDIA_OBJETIVAS
0,206403,23052929.0,2301406.0,Aratuba,23.0,2.0,1.0,1.0,427.1,436.8,377.8,423.4,300.0,80.0,60.0,60.0,80.0,20.0,393.02,416.275
1,3604651,42103770.0,4218004.0,Tijucas,42.0,4.0,1.0,1.0,689.2,521.9,601.9,605.5,920.0,160.0,200.0,200.0,180.0,180.0,667.70,604.625
2,1461268,nan,nan,NaN,nan,nan,nan,nan,456.4,363.0,548.4,557.2,480.0,120.0,120.0,40.0,120.0,80.0,481.00,481.250
3,4301058,nan,nan,NaN,nan,nan,nan,nan,629.1,550.7,553.8,605.9,740.0,140.0,200.0,160.0,160.0,80.0,615.90,584.875
7,140768,nan,nan,NaN,nan,nan,nan,nan,496.7,482.7,531.6,439.2,360.0,100.0,80.0,60.0,120.0,0.0,462.04,487.550

In [39]:
# Novas estatísticas descritivas para as novas colunas
df_enem_filtrado[['NU_NOTA_MEDIA_GERAL', 'NU_NOTA_MEDIA_OBJETIVAS']].describe()

       NU_NOTA_MEDIA_GERAL  NU_NOTA_MEDIA_OBJETIVAS
count         2.990093e+06             2.990093e+06
mean          5.393216e+02             5.154855e+02
std           9.132661e+01             7.637700e+01
min           0.000000e+00             0.000000e+00
25%           4.763800e+02             4.565000e+02
50%           5.347200e+02             5.049500e+02
75%           6.021000e+02             5.675750e+02
max           8.598000e+02             8.447500e+02